FROM bitnami/kafka:3.1

# CMD ["./opt/bitnami/kafka/bin/kafka-topics.sh", "--bootstrap-server", "zookeeper:2181", "--create", "--topic", "spark-output", "--if-not-exists", "--partitions", "3", "--replication-factor", "3"]
# CMD ["./bin/kafka-topics.sh", "--create", "--topic", "all-messages", "--if-not-exists", "--partitions", "1", "--replication-factor", "3"]
